apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-service
  labels:
    app: load-service
spec:
  replicas: 10
  selector:
    matchLabels:
      app: load-service
  template:
    metadata:
      labels:
        app: load-service
    spec:
      containers:
      - name: load-service
        image: kritid9/load-testing:v2
